# Single source of truth for neighborhood mapping (EN -> HE).
NEIGHBORHOOD_EN_TO_HE = {
  "Abu Kabir": "אבו כביר",
  "Ohel Moshe": "אוהל משה",
  "Ofek HaYam": "אופק הים",
  "Orot": "אורות",
  "Yarkon Industrial Zone": "אזור תעשייה עבר הירקון",
  "Azorei Hen": "אזורי חן",
  "Afeka": "אפקה",
  "Bitzaron": "ביצרון",
  "Givat Aliya": "גבעת עלייה",
  "Givat Herzl": "גבעת הרצל",
  "Givat Amal B": "גבעת עמל ב'",
  "HaMishtala": "המשתלה",
  "The New North": "הצפון החדש",
  "The Old North": "הצפון הישן",
  "HaKirya": "הקריה",
  "Yad Eliyahu": "יד אליהו",
  "Jaffa G": "יפו ג'",
  "Jaffa D": "יפו ד'",
  "Yashgav": "ישגב",
  "Kochav HaTzafon": "כוכב הצפון",
  "Kfar Shalem": "כפר שלם",
  "Kerem HaTeimanim": "כרם התימנים",
  "Kerem Yisrael": "כרם ישראל",
  "Kerem Moshe": "כרם משה",
  "Lev Tel Aviv (City Center)": "לב תל אביב",
  "Mea Shearim": "מאה שערים",
  "Migdaley Ne'eman": "מגדלי נאמן",
  "Machane Yehuda": "מחנה יהודה",
  "Machane Yosef": "מחנה יוסף",
  "Manshiya (Jaffa)": "מנשייה (יפו)",
  "Maoz Aviv": "מעוז אביב",
  "Merkaz Ba'alei Melacha": "מרכז בעלי מלאכה",
  "Merkaz Miskhari": "מרכז מסחרי",
  "Hasan Arafe Compound": "מתחם חסן ערפה",
  "Lodoweepol Compound": "מתחם לודוויפול",
  "Neot Afeka": "נאות אפקה",
  "Nachalat Binyamin": "נחלת בנימין",
  "Nachalat Yitzhak": "נחלת יצחק",
  "Neve Avivim": "נווה אביבים",
  "Neve Eliezer": "נווה אליעזר",
  "Neve Barbur": "נווה ברבור",
  "Neve Chen": "נווה חן",
  "Neve Kfir": "נווה כפיר",
  "Neve Ofer": "נווה עופר",
  "Neve Tzedek": "נווה צדק",
  "Neve Tzahal": "נווה צה\"ל",
  "Neve Shaanan": "נווה שאנן",
  "Neve Shalom": "נווה שלום",
  "Neve Sharett": "נווה שרת",
  "Nofei Yam": "נופי ים",
  "Nordia": "נורדיה",
  "Sakanat Al-Turki": "סכנת א-תורכי",
  "Park Tzameret": "פארק צמרת",
  "Florentin": "פלורנטין",
  "Pardes Daka": "פרדס דכה",
  "Tzahala": "צהלה",
  "Tzahal On": "צהלון",
  "Tzukey Aviv": "צוקי אביב",
  "Kiryat HaMelekha": "קריית המלאכה",
  "Kiryat Meir": "קריית מאיר",
  "Kiryat Shaul": "קריית שאול",
  "Kiryat Shalom": "קריית שלום",
  "Ramat Aviv": "רמת אביב",
  "Ramat Aviv G": "רמת אביב ג'",
  "Ramat HaHayal": "רמת החייל",
  "Ramat HaTayasim": "רמת הטייסים",
  "Ramat HaSharon": "רמת השרון",
  "Ramat Yisrael": "רמת ישראל",
  "Shikun Bavli": "שיכון בבלי",
  "Shikun Dan": "שיכון דן",
  "Shikun Tzameret": "שיכון צמרת",
  "Shikuney Chisachon": "שיכוני חיסכון",
  "Ahuva": "אחווה",
  "HaArgazim": "הארגזים",
  "HaTikva": "התקווה",
  "Yedidya": "ידידיה",
  "Lamed": "למד",
  "Montefiore": "מונטיפיורי",
  "Machlol": "מחלול",
  "Ezra": "עזרא",
  "Pakidei Apak": "פקידי אפ\"ק",
  "Revivim": "רביבים",
  "Shabazi": "שבזי",
  "Shpak": "שפאק",
  "Shapira": "שפירא",
  "Tel Baruch": "תל ברוך",
  "Tel Haim": "תל חיים",
  "Tel Nordau": "תל נורדאו"
}
