# Single source of truth for neighborhood mapping (EN -> HE).
NEIGHBORHOOD_EN_TO_HE = {
    "Lev Ha'Ir (City Center)": "לב העיר",
    "Neve Tzedek": "נווה צדק",
    "Shabazi Quarter": "שכונת שבזי",
    "Kerem HaTeimanim": "כרם התימנים",
    "Kerem Yisrael": "כרם ישראל",
    "Ramat HaSharon Quarter": "שכונת רמת השרון",
    "Tel Nordau": "תל נורדאו",
    "Montefiore Quarter": "שכונת מונטיפיורי",
    "HaKirya & Sarona": "הקריה ושרונה",
    "Kiryat Meir": "קריית מאיר",
    "The Old North": "הצפון הישן",
    "The New North": "הצפון החדש",
    "Bavli": "שיכון בבלי",
    "Givat Amal B": "גבעת עמל ב'",
    "Park Tzameret": "פארק צמרת",
    "Florentin": "פלורנטין",
    "Neve Sha’anan": "נווה שאנן",
    "Shapira Quarter": "שכונת שפירא",
    "Kiryat Shalom": "קריית שלום",
    "Neve Ofer": "נווה עופר",
    "Givat Herzl": "גבעת הרצל",
    "Kiryat HaMelekha": "קריית המלאכה",
    "HaRakevet Quarter": "שכונת הרכבת",
    "Old Jaffa": "יפו העתיקה",
    "Jaffa A (Dekel)": "יפו א' (דקר)",
    "Jaffa G": "יפו ג'",
    "Jaffa D": "יפו ד'",
    "Ajami": "עג'מי",
    "Givat Aliyah": "גבעת עלייה",
    "Tzahalon": "צהלון",
    "Shikuney Chisachon": "שיכוני חיסכון",
    "Pardes Daka": "פרדס דכה",
    "Givat Andromeda": "גבעת אנדרומדה",
    "Manshiya": "מנשייה",
    "American Colony": "המושבה האמריקאית",
    "Yad Eliyahu": "יד אליהו",
    "HaTikva Quarter": "שכונת התקווה",
    "Kfar Shalem": "כפר שלם",
    "Bitzaron": "ביצרון",
    "Nachalat Yitzhak": "נחלת יצחק",
    "Ramat Yisrael": "רמת ישראל",
    "Beit Yaakov": "בית יעקב",
    "Neve Tzahal": "נווה צה\"ל",
    "Neve Kfir": "נווה כפיר",
    "Neve Barbur": "נווה בארבור",
    "Orot": "אורות",
    "Neve Eliezer": "נווה אליעזר",
    "Neve Chen": "נווה חן",
    "Nir Aviv": "ניר אביב",
    "Ramat HaTayasim": "רמת הטייסים",
    "Tel Haim": "תל חיים",
    "Shikun Amami G": "שיכון עממי ג'",
    "Ezra Quarter": "שכונת עזרא",
    "HaArgazim Quarter": "שכונת הארגזים",
    "Levana Quarter": "שכונת לבנה",
    "Yedidya Quarter": "שכונת ידידיה",
    "Ramat Aviv": "רמת אביב",
    "Neve Avivim": "נווה אביבים",
    "Ramat Aviv G": "רמת אביב ג'",
    "New Ramat Aviv": "רמת אביב החדשה",
    "Afeka": "אפקה",
    "Lamed Quarter": "שכונת למד",
    "Kochav HaTzafon": "כוכב הצפון",
    "Nofei Yam": "נופי ים",
    "Tzukey Aviv": "צוקי אביב",
    "Azorei Chen": "אזורי חן",
    "New Gimel": "גימל החדשה",
    "Ne’eman Towers": "מגדלי נאמן",
    "Sea & Sun": "סי אנד סאן",
    "Glilot": "גלילות",
    "University Quarter": "קריית האוניברסיטה",
    "Tel Baruch": "תל ברוך",
    "Maoz Aviv": "מעוז אביב",
    "Hadar Yosef": "הדר יוסף",
    "Neot Afeka": "נאות אפקה",
    "Revivim Quarter": "שכונת רביבים",
    "Tzahala": "צהלה",
    "HaMishtala": "המשתלה",
    "Neve Sharett": "נווה שרת",
    "Shikun Dan": "שיכון דן",
    "Yashgav": "ישגב",
    "Ramat HaChayal": "רמת החייל",
    "Kiryat Atidim": "קריית עתידים"
}
